### ISSUE TITLE
question about search model code?

### ISSUE THREAD

**Issue by qinb** [D-X-Y/NAS-Projects#21]
Hi Buddy, Thanks for your great work! 
Do you plan to share your search model code ?  and what time about it? looking forward to your answer !

**Comment by D-X-Y** [comment]
Hi, @qinb , we just released the searching codes for TAS (https://github.com/D-X-Y/NAS-Projects#network-pruning-via-transformable-architecture-search). We will release SETN and GDAS soon.

**Comment by xieydd** [comment]
Awesome work.

**Comment by D-X-Y** [comment]
@qinb Please find the searching codes here: https://github.com/D-X-Y/NAS-Projects#usage-2
