### ISSUE TITLE
Does TAS apply weight sharing?

### ISSUE THREAD

**Issue by Hanson13** [D-X-Y/NAS-Projects#29]
Hi, Thank you for your excellent work!
While searching for width, I wonder whether the operations with different channel numbers share the weight from the one-shot network? If yes, how does the weight in the one-shot network get updated, since it has K(K=2 in your framework figure) gradients separately from the K sampled operation?
Btw, "When τ-> 0, p^ = [^ p1; :::; p^j; :::] becomes one-shot, and the Gumbel-softmax distribution...", do you mean "one-hot" instead of "one-shot"?

**Comment by D-X-Y** [comment]
1, yes. They share the weights, please refer to https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/searchs/SearchCifarResNet_width.py#L81 .

2, Yes, it is a type and should be one-hot
