### ISSUE TITLE
Where is cifar10-0.5.pth?

### ISSUE THREAD

**Issue by Hanson13** [D-X-Y/NAS-Projects#30]
Hi, when I run "CUDA_VISIBLE_DEVICES=0,1 bash ./scripts-search/search-depth-gumbel.sh cifar10 ResNet110 CIFARX 0.57 -1", I got the following error:

Traceback (most recent call last):
  File "./exps/search-shape.py", line 202, in <module>
    main(args)
  File "./exps/search-shape.py", line 40, in main
    assert split_file_path.exists(), '{:} does not exist'.format(split_file_path)
AssertionError: .latent-data/splits/cifar10-0.5.pth does not exist

However, I didn't find the file in the Google Driver URL, is it renamed to another file?
Thank you!

**Comment by D-X-Y** [comment]
Please run `bash ./scripts/prepare.sh` in the root directory. This script will automatically generate `.latent-data/splits/cifar10-0.5.pth`.
