### ISSUE TITLE
Is there any pretrained model after searching for width or depth released?

### ISSUE THREAD

**Issue by Hanson13** [D-X-Y/NAS-Projects#31]
Hi, I check the .pth files in the Google Driver URL(like files in the basic-results directory), and find that they have weights with the same shape and depth with the standard model. So I guess that they are models before searching. Does I mistake it or is there any pretrained model after searching for width depth released?
Thank you for your help!

**Comment by D-X-Y** [comment]
Hi @Hanson13 , the pre-trained model is of the unpruned network.
Our TAS consists of three steps.
(1) Pre-train the unpruned network (provided in Google Driver).
(2) Search the depth and width of the network following https://github.com/D-X-Y/NAS-Projects#usage
(3) Distill the knowledge from the unpruned network (you can train by yourself or using our provided one) to the network (whose depth and width are searched by step-2).

**Comment by D-X-Y** [comment]
Close at inactive for 7 days. Please feel free to re-open it.
