### ISSUE TITLE
Missing Structure object?

### ISSUE THREAD

**Issue by auroua** [D-X-Y/NAS-Projects#32]
In file `search_model_gdas.py` in lib/models/cell_searchs package. 
```
from .genotypes import Structure
```
I can not find the `Structure` object. Could you share this file?

**Comment by auroua** [comment]
The method `forward_gdas ` in `SearchCell` class doesn't exists too.
Could you share this method? 
Thanks!

**Comment by auroua** [comment]
Thanks.

**Comment by D-X-Y** [comment]
@auroua Please find the functions at https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/cell_searchs/search_cells.py#L47
