### ISSUE TITLE
channel wise interpolation (CWI)

### ISSUE THREAD

**Issue by AllanWlz** [D-X-Y/NAS-Projects#37]
Hi, Xuanyi. Could you please provide more details about CWI?  I meet problem reading the http://arxiv.org/abs/1905.09717

**Comment by D-X-Y** [comment]
All source codes have been released. What details do you want to know?

**Comment by AllanWlz** [comment]
https://github.com/D-X-Y/NAS-Projects/tree/master/exps/algos
Is the code in url above?
Sorry, but I didn't find the algo in http://arxiv.org/abs/1905.09717.

**Comment by D-X-Y** [comment]
Please follow the instructions here: https://github.com/D-X-Y/NAS-Projects#network-pruning-via-transformable-architecture-search

**Comment by D-X-Y** [comment]
Feel free to re-open this issue if you have further questions.
