### ISSUE TITLE
How to train the model I searched?

### ISSUE THREAD

**Issue by Debrove** [D-X-Y/NAS-Projects#40]
Thanks for your excellent works. 

In SETN, as a newcomer to NAS, I am confused that I can't find a way to train the model I have searched. I run the scripts of training and searching respectively, which just train the default searched model instead of my searched model.

Thank you.

**Comment by D-X-Y** [comment]
Do you mean you want to train the model searched by these scripts (https://github.com/D-X-Y/NAS-Projects/tree/master/scripts-search/algos)?

**Comment by Debrove** [comment]
Yes.

**Comment by shashank3959** [comment]
I'm currently deep into the code too trying to train the model I searched. 
The file https://github.com/D-X-Y/NAS-Projects/blob/master/lib/nas_infer_model/DXYs/genotypes.py looks like it has manually populated the searched architecture. If we have searched our own architecture, shall we make a similar entry manually?

**Comment by shashank3959** [comment]
This is really good work btw!

Another question I have is that in GDAS, do we assume a fixed reduction cell as opposed to searching for one?

**Comment by D-X-Y** [comment]
@Debrove Thanks for your interest. This repo contains many algorithms.
I will prepare script to train the searched model soon.

@shashank3959 
In GDAS, we can search for both normal/reduction cells or only search for the nomral-cell with a fixed reduction cell.
If you follow the instruction in README, it will automatically search for a tiny network instead of the structure in the paper. This is for fairly compare ours with other 10 NAS algorithms.

**Comment by D-X-Y** [comment]
@Debrove Thanks a lot for your interest. I will update the codes right after Dec 20. Due to some restrictions, I cannot release parts of the code at the moment. Sorry for the inconvenience.

**Comment by Debrove** [comment]
@D-X-Y Thank you very much.

**Comment by D-X-Y** [comment]
@Debrove I have updated the README. You can follow https://github.com/D-X-Y/NAS-Projects#training-the-searched-architecture to train your searched model.
BTW: the current search space in this repo is the one in our recent paper "NAS-Bench-102: Extending the Scope of Reproducible Neural Architecture Search".
