### ISSUE TITLE
Can not find the papar 'GDAS'

### ISSUE THREAD

**Issue by xingyueye** [D-X-Y/NAS-Projects#47]
Sorry to trouble you, But I have a little confusion about the papar GDAS. I find that I can't find the paper " Gradient-based search using Differentiable Architecture Sampler" anymore, Is it the same paper as "Searching for A Robust Neural Architecture in Four GPU Hours"?

**Comment by D-X-Y** [comment]
Hi, "Gradient-based search using Differentiable Architecture Sampler" is the name of our method, the paper title is "Searching for A Robust Neural Architecture in Four GPU Hours".

**Comment by D-X-Y** [comment]
@xingyueye I will close this issue. Please feel free to re-open it if you have further questions.
